# Required
version: 2

build:
  os: ubuntu-22.04
  tools: 
    python: "3.8"
# python:
#   version: 3.8
#   pip_install: true
#   extra_requirements:
#     - docs
python:
  install:
    - method: pip
      path: .
      extra_requirements:
        - docs
    - method: pip