# This workflow will build the package.

name: build

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.8
      uses: actions/setup-python@v4
      with:
        python-version: 3.8
    - name: Install dependencies
      run: |
        pip install poetry
        poetry install
    - name: Test with pytest
      run: poetry run pytest
    - name: Bump version and tagging and publish
      run: |
        pip install python-semantic-release
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        semantic-release publish